submit : http://10.10.10.185:9008/dep-page-service/submit
submitAll : http://10.10.10.185:9008/dep-page-service/submitAll
cg1001 : http://10.10.10.185:10003/services/cgbiz/cg1001
cg2001 : http://10.10.10.185:10003/services/cgbiz/cg2001
cg2002 : http://10.10.10.185:10003/services/cgbiz/cg2002
cg1044 : http://10.10.10.185:9008/dep-page-service/cg1044
target_url: http://10.10.10.185:10003/services/cgbiz/
url:
    request_url :  http://10.10.10.185:10003/services/cgbiz/
    sign_url :
    encrypt_json_url :
    encrypt_key_url :
excel:
    case_path : 'E:\\Git\\JYTest\\testdata\\interface\\case.xlsx'
email:
    email_server : smtp.163.com
    email_on_off : 'off'
    email_sender : 18392169938@163.com
    email_password :
    email_receiver : wangqunsong@jytpay.com
    email_subject : 'JYT--接口测试报告'
    email_content :
log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'